### ISSUE TITLE
Evaluate the code of Temporal Blocking

### ISSUE THREAD

**Issue by hrontan** [endowataru/laplace#1]
Evaluate the code of Temporal Blocking on Bridge or Reedbush.
758025bf6dfe9dfe42e7d0110c16f3f83e9b1b37

**Comment by MasatakaYm** [comment]
116,117行目: max, min -> fmax, fminに変更
117行目: セミコロンが抜けてる

Bridgeでの実行結果は以下のとおり
Running on 4 MPI processes
Max error at iteration 3264 was  0.00999899724298103
Total time was 1.704084 seconds.
PE 3: T(504,622) = 15.513749 (0.000000)

**Comment by endowataru** [comment]
0969f691067f7c25be52d0639915b68820ba7d42
